export const users = [
  {
    id: 1,
    firstName: "Aarav",
    lastName: "Sharma",
    email: "aarav.sharma@example.com",
    age: 26,
    city: "Mumbai",
    isActive: true,
  },
  {
    id: 2,
    firstName: "Priya",
    lastName: "Verma",
    email: "priya.verma@example.com",
    age: 29,
    city: "Delhi",
    isActive: true,
  },
  {
    id: 3,
    firstName: "Rahul",
    lastName: "Mehta",
    email: "rahul.mehta@example.com",
    age: 31,
    city: "Pune",
    isActive: false,
  },
  {
    id: 4,
    firstName: "Sneha",
    lastName: "Nair",
    email: "sneha.nair@example.com",
    age: 24,
    city: "Bangalore",
    isActive: true,
  },
  {
    id: 5,
    firstName: "Rohan",
    lastName: "Patel",
    email: "rohan.patel@example.com",
    age: 28,
    city: "Ahmedabad",
    isActive: false,
  },
  {
    id: 6,
    firstName: "Kavya",
    lastName: "Iyer",
    email: "kavya.iyer@example.com",
    age: 22,
    city: "Chennai",
    isActive: true,
  },
  {
    id: 7,
    firstName: "Aditya",
    lastName: "Joshi",
    email: "aditya.joshi@example.com",
    age: 27,
    city: "Nagpur",
    isActive: true,
  },
  {
    id: 8,
    firstName: "Neha",
    lastName: "Kapoor",
    email: "neha.kapoor@example.com",
    age: 25,
    city: "Lucknow",
    isActive: false,
  },
  {
    id: 9,
    firstName: "Vikram",
    lastName: "Singh",
    email: "vikram.singh@example.com",
    age: 30,
    city: "Chandigarh",
    isActive: true,
  },
  {
    id: 10,
    firstName: "Ananya",
    lastName: "Rao",
    email: "ananya.rao@example.com",
    age: 23,
    city: "Hyderabad",
    isActive: true,
  },
  {
    id: 11,
    firstName: "Manish",
    lastName: "Kumar",
    email: "manish.kumar@example.com",
    age: 33,
    city: "Patna",
    isActive: false,
  },
  {
    id: 12,
    firstName: "Pooja",
    lastName: "Das",
    email: "pooja.das@example.com",
    age: 21,
    city: "Kolkata",
    isActive: true,
  },
  {
    id: 13,
    firstName: "Arjun",
    lastName: "Yadav",
    email: "arjun.yadav@example.com",
    age: 29,
    city: "Indore",
    isActive: true,
  },
  {
    id: 14,
    firstName: "Divya",
    lastName: "Bansal",
    email: "divya.bansal@example.com",
    age: 27,
    city: "Jaipur",
    isActive: false,
  },
  {
    id: 15,
    firstName: "Harsh",
    lastName: "Malhotra",
    email: "harsh.malhotra@example.com",
    age: 32,
    city: "Bhopal",
    isActive: true,
  },
  {
    id: 16,
    firstName: "Ritu",
    lastName: "Garg",
    email: "ritu.garg@example.com",
    age: 24,
    city: "Surat",
    isActive: true,
  },
  {
    id: 17,
    firstName: "Nikhil",
    lastName: "Chauhan",
    email: "nikhil.chauhan@example.com",
    age: 28,
    city: "Noida",
    isActive: false,
  },
  {
    id: 18,
    firstName: "Aisha",
    lastName: "Ali",
    email: "aisha.ali@example.com",
    age: 26,
    city: "Thane",
    isActive: true,
  },
  {
    id: 19,
    firstName: "Siddharth",
    lastName: "Tiwari",
    email: "siddharth.tiwari@example.com",
    age: 30,
    city: "Kanpur",
    isActive: true,
  },
  {
    id: 20,
    firstName: "Meera",
    lastName: "Jain",
    email: "meera.jain@example.com",
    age: 25,
    city: "Nashik",
    isActive: false,
  },
];
